### ISSUE TITLE
When clicking login button, I am getting 401 unauthorized

### ISSUE THREAD

**Issue by DanceParty** [cicorias/react-azuread-passport#4]
When I start your app, I am able to connect everything and get it working. However, I am trying to connect with `create-react-app` and I am setting everything up the same, but instead of working, when clicking the login button I get

```
xhr.js:179 GET http://localhost:8080/api/profile 401 (Unauthorized)
```

Any advice? My ultimate goal is to separate the client and server so we can be hitting this login server with multiple clients

**Comment by DanceParty** [comment]
Tweaking some things has now gotten me passed this error, but now what is happening is

1. Navigation Component makes an axios.get() request, returns a response, but without any data.

2. When hitting this line: `const { firstName, lastName, email } = response.data.user` there is no data, causing an error to be thrown `Cannot read property 'firstName' of undefined`

Now here is where I would expect the behavior to be:

- User is sent back to the Login page where pressing the login button will call `this.loginToADFS.bind(this)` and then `window.location = '/auth/login-adfs'

But instead the server is throwing the error

```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (C:\Users\keevandance\Documents\Github\test-azure\node_modules\express\lib\response.js:767:10)
    at ServerResponse.send (C:\Users\keevandance\Documents\Github\test-azure\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (C:\Users\keevandance\Documents\Github\test-azure\node_modules\express\lib\response.js:267:15)
    at C:\Users\keevandance\Documents\Github\test-azure\server\middleware\error.js:4:9
    at Layer.handle_error (C:\Users\keevandance\Documents\Github\test-azure\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\keevandance\Documents\Github\test-azure\node_modules\express\lib\router\index.js:315:13)
    at C:\Users\keevandance\Documents\Github\test-azure\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\keevandance\Documents\Github\test-azure\node_modules\express\lib\router\index.js:335:12)
    at Immediate.next (C:\Users\keevandance\Documents\Github\test-azure\node_modules\express\lib\router\index.js:275:10)
```

**Comment by DanceParty** [comment]
Update 3: 

I have gotten everything working (it is grabbing user information like email, name, etc.. and I can see it in the console), but instead of redirecting my application back to localhost:3000, it is redirecting to localhost:8080 and I am not sure why or how to do that any differently? 

I believe this is some configuration on manage.windowsazure.com, but if I don't have the localhost:8080 as a reply url, then it does not work. 

Any help is EXTREMELY appreciated :)

**Comment by cicorias** [comment]
I apoligize - i never saw this - if there's a chance you still need help let me know here.. I've turned on monitoring/notifications
